import type { ReportSource } from '@/features/research/types';

type SourcesListProps = {
  sources: ReportSource[];
};

const SOURCE_TYPE_LABELS: Record<ReportSource['type'], string> = {
  filing: 'SEC Filing',
  press_release: 'Press Release',
  ir_page: 'Investor Relations',
  news: 'News',
  other: 'Other'
};

export default function SourcesList({ sources }: SourcesListProps) {
  if (sources.length === 0) return null;

  return (
    <section className="space-y-4" id="sources">
      <h2 className="text-2xl font-semibold text-slate-100 gradient-text">Sources</h2>
      <div className="rounded-lg border border-slate-700 bg-slate-900/40 p-6">
        <div className="grid gap-4">
          {sources.map((source, idx) => (
            <div key={source.id} className="flex items-start gap-3 text-sm">
              <span className="flex-shrink-0 w-8 text-slate-500 font-mono">[{idx + 1}]</span>
              <div className="flex-1 space-y-1">
                <div className="flex items-center gap-2 flex-wrap">
                  <a
                    href={source.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-emerald-300 hover:text-emerald-200 font-medium"
                  >
                    {source.title}
                  </a>
                  <span className="px-2 py-0.5 bg-slate-700/50 text-slate-400 text-xs rounded">
                    {SOURCE_TYPE_LABELS[source.type]}
                  </span>
                </div>
                {source.excerpt && (
                  <p className="text-slate-400 text-xs">{source.excerpt}</p>
                )}
              </div>
            </div>
          ))}
        </div>
        <div className="mt-6 pt-4 border-t border-slate-700 text-xs text-slate-500">
          <p>
            <strong>Note:</strong> This research report is generated by AI for informational
            purposes only and does not constitute financial advice. Always conduct your own research
            and consult with qualified financial advisors before making investment decisions.
          </p>
        </div>
      </div>
    </section>
  );
}